### ISSUE TITLE
Needs a lot of improvements

### ISSUE THREAD

**Issue by ahhda** [ravaan/Design-Patterns#1]
* No license
* Incomplete README
* Spelling mistakes in commits
![Screenshot 2020-04-20 at 12 22 46 AM](https://user-images.githubusercontent.com/7795956/79696943-64276080-829d-11ea-80a2-5799f72b06f8.png)

**Comment by ravaan** [comment]
God damn

**Comment by ravaan** [comment]
@ahhda please review and feel free to raise another issue if you find one <.((()><
